#!/bin/sh
set -x
rm -rf ./config.cache

if [ x"$1" = x ]; then
  name=`uname -n`
else
  if [ x"$1" = x"--" ]; then
    name=`uname -n`
  else
    name="$1"
  fi
  shift
fi

PRODFLAGS="-O2"
DEVFLAGS="-g -W -Wall -Wno-implicit-int"
LDFLAGS="-g"
export LDFLAGS

CF="--config-cache"

echo "configure for: " $name
case $name in
  saord*)
  ./configure 	$CF						\
		--prefix=/soft/saord				\
		--with-cfitsio=/proj/rd/linux64			\
      		CC=gcc CFLAGS="$PRODFLAGS"			\
 		$*
  ;;

  bokhara*)
  ./configure 	$CF						\
		--prefix=$HOME					\
		--with-cfitsio=/proj/rd/linux64			\
  		CC=gcc CFLAGS="$DEVFLAGS"			\
 		$*
  ;;

  js9)
  ./configure 	$CF					\
		--prefix=$HOME				\
		--with-cfitsio=$HOME			\
		--with-filter-cflags="-O2"		\
		CC=gcc CFLAGS="$CFLAGS $PRODFLAGS"	\
		$*
  ;;

  baba*)
  ./configure 	$CF						\
		--prefix=$HOME					\
		--with-cfitsio=$HOME				\
		CC=cc CFLAGS="$DEVFLAGS" 			\
		$*
  ;;

  luke*|han*)
  ./configure 	$CF						\
		--prefix=/pool14/eric				\
		--with-cfitsio=/proj/rd/solaris			\
  		CC=gcc CFLAGS="$DEVFLAGS"			\
 		$*
  ;;

  smartx*)
  ./configure   $CF                                                     \
                --prefix=/smartx                                        \
                --with-cfitsio=/smartx/cfitsio                          \
		--with-filter-cflags="-O2"				\
                CC=gcc CFLAGS="$CFLAGS $PRODFLAGS"                      \
                $*
  ;;

  *)
  ./configure 	$CF $*
  ;;

esac
